version: 1
disable_existing_loggers: False

formatters:
  simpleFormatter:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simpleFormatter
    stream: ext://sys.stdout

  fileHandler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simpleFormatter
    filename: app.log
    mode: 'a'
    maxBytes: 10485760  # 10 MB
    backupCount: 5

loggers:
  root:
    level: DEBUG
    handlers: [consoleHandler, fileHandler]